package benchmarkdp.datagenerator.app.state;

public enum ExperimentState {

	START,
	FOLDER_STRUCTURE_INITIALIZED,
	TEST_CASES_INITIALIZED,
	TEST_CASES_MUTATED,
	TEST_CASES_DISTRIBUTED,
	TEST_CASES_COLLECTED,
	TEST_CASES_FITSDONE,
	TEST_CASES_FINALIZED
}
